### ISSUE TITLE
Add ability to output alternative file names for BOMs

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#104]
According to [the recognized file patterns documentation](https://cyclonedx.org/specification/overview/#recognized-file-patterns), the following patterns are allowed

- `*.cdx.json` for `JSON` encoded CycloneDX BOM files.
- `*.cdx.xml` for `XML` encoded CycloneDX BOM files.

Currently, we always output `bom.json`/`bom.xml`

### Acceptance Criteria

- [ ] Configure the output to be `<package name>.cdx.json`/`<package name>.cdx.xml`
- [ ] Configure the output to have a specific filename prefix of `<prefix name>.cdx.json`/`<prefix name>.cdx.xml`
- [ ] These configurations should be supported via the CLI and `Cargo.toml` (#103) approaches to configuration.

**Comment by allisonsierra** [comment]
I'm interested in working on this one.
