### ISSUE TITLE
Implement validation functionality for the cyclonedx-bom library's internal model

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#106]
As part of the library-ification project (#68), we want to be lenient in what we accept and strict in what we execute. In order to fulfill that philosophy, we want to implement validation functionality, so that a user can ensure the data they have received conforms to the specification, if that is important to them.

This validation should live on the internal model and should share functionality with the logic used to ensure that library-consumer generated SBOMs are correct by construction. A potential library to aid with this purpose is [validator](https://github.com/Keats/validator), but other alternatives may also be appropriate.

A hypothetical workflow is

``` rust
let bom = cyclonedx_bom::parse_xml(bom_file)?;
match bom.validate() {
    Ok(bom) => todo!("add vulnerability data"),
    Err(validation_errors) => todo!("Display invalid data errors to the user"),
}
```

This will be done based on the work in #105

### Acceptance Criteria

- [ ] All of the validation cases described in the XML and JSON specifications are applied to the internal model when the `.validate()` function is called
- [ ] The same logic is applied to any functions that are used by library consumers when constructing `model::Bom` and related values

**Comment by allisonsierra** [comment]
I am interested on working on this one.
