### ISSUE TITLE
Licensing format mismatch

### ISSUE THREAD

**Issue by UgniusV** [CycloneDX/cyclonedx-rust-cargo#121]
Hello 👋 I have noticed that licensing information is formatted in an odd manner. For example when using rust-cargo scanner the licensing information is formatted in a following way:
```
    {
      "name": "byte-unit",
      "version": "4.0.13",
      "description": "A library for interaction with units of bytes.",
      "purl": "pkg:cargo/byte-unit@4.0.13",
      "type": "library",
      "scope": "required",
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
      "externalReferences": [
        {
          "type": "website",
          "url": "https://magiclen.org/byte-unit"
        },
        {
          "type": "vcs",
          "url": "https://github.com/magiclen/byte-unit"
        }
      ]
    },
```
However, when using golang scanner from https://github.com/CycloneDX/cyclonedx-gomod the licensing information is formatted differently.
```
    {
      "bom-ref": "pkg:golang/github.com/klauspost/compress@v1.13.6?type=module",
      "type": "library",
      "name": "github.com/klauspost/compress",
      "version": "v1.13.6",
      "scope": "required",
      "hashes": [
        {
          "alg": "SHA-256",
          "content": "3fbe82a292442d2d1388eda679b9a7ce059a6a3b2c3ff12cce996db604317207"
        }
      ],
      "purl": "pkg:golang/github.com/klauspost/compress@v1.13.6?type=module",
      "externalReferences": [
        {
          "url": "https://github.com/klauspost/compress",
          "type": "vcs"
        }
      ],
      "evidence": {
        "licenses": [
          {
            "license": {
              "id": "Apache-2.0"
            }
          }
        ]
      }
    },
```
As you can see the difference is in license JSON object. Rust-cargo scanner formats licensing information using:
```
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
```
while golang scanner formats licensing information by wrapping it inside evidence JSON object:
```
      "evidence": {
        "licenses": [
          {
            "license": {
              "id": "Apache-2.0"
            }
          }
        ]
      }
```
Why is there a mismatch? Shouldn't the licensing structure be the same? Also when uploading SBOM generated by rust-scanner to Dependency-Track the licensing information is not shown in Dependency-Track. While uploading SBOMs generated by the golang scanner to Dependency-Track - the Licensing information is present. It seems like Dependency-Track doesn't like the following format:
```
      "licenses": [
        {
          "expression": "MIT"
        }
      ],
```
But prefers this one:
```
      "evidence": {
        "licenses": [
          {
            "license": {
              "id": "Apache-2.0"
            }
          }
        ]
      }
```
Is there an option to combat this behaviour? Or is there a possibility to add a CLI switch for licensing formatting?

**Comment by stevespringett** [comment]
I'll let the maintainers comment on the implementation differences, but Dependency Track does not currently support expressions or evidence, only license id and name.

**Comment by amy-keibler** [comment]
Hello! Thank you for opening an issue. We output licenses as expressions, because the [Cargo manifest format definition of the `license` field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) indicates that it will be a SPDX license expression. The Rust community tends to default to `MIT OR Apache-2.0` by community convention, so this field will probably rarely be a single license.

@stevespringett is there a play for Dependency Track to support license expressions?

We could probably use something like the [`spdx` crate](https://crates.io/crates/spdx) to parse the expression into individual licenses and emit a single license where possible as a compatibility solution, but we might not be able to handle complex SPDX expressions (e.g. ones containing `AND`, `OR`, or `WITH` clauses).

**Comment by stevespringett** [comment]
Yes, Dependency-Track will eventually support SPDX license expressions. Currently it's limited to a single SPDX ID, or an unresolved license name. IMO, I would leave the current rust implementation as-is, because its outputting exactly what it should be.

**Comment by UgniusV** [comment]
Great, thanks for the information!
