### ISSUE TITLE
Add cargo-cyclonedx to the tools metadata

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#130]
Other libraries add the tool information to the generated BOM. We should do that with the values

- `vendor: "CycloneDX"`
- `name: "cargo-cyclonedx"`
- `version: env!("CARGO_PKG_VERSION")` ([reference](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates))

#### Examples of other CycloneDX projects:

- Python: [here](https://github.com/CycloneDX/cyclonedx-python/blob/a527e0df9d83ca2c756cac19079c00a59ad21d55/cyclonedx_py/client.py#L93)
- Node: [here](https://github.com/CycloneDX/cyclonedx-node-module/blob/f033cd5416bf9236119474a2cd74e96e86a8a0fc/model/Bom.js#L54)

**Comment by allisonsierra** [comment]
I will take this one.
