### ISSUE TITLE
Add support for dependency graph introduced in v1.2 of the spec

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/cyclonedx-rust-cargo#14]

**Comment by amy-keibler** [comment]
The [XML schema definition](https://cyclonedx.org/docs/1.3/xml/#type_dependenciesType) and the [JSON schema definition](https://cyclonedx.org/docs/1.3/json/#dependencies) are good starting points.

You'll want to run with the `--all` flag (e.g. `cargo run -- cyclonedx --all`) to generate the full dependency list. You can visually spot-check your output dependency graph using [`cargo tree`](https://doc.rust-lang.org/cargo/commands/cargo-tree.html) to ensure the graph is constructed correctly.

The relevant code is in `generator.rs`. This will require some refactoring to support retaining the dependency relationships when processing the cargo manifest files.

**Comment by monokles** [comment]
Hey! I see that there already exists a PR for this issue, which is awesome. Are there any blockers for merging?
