### ISSUE TITLE
How to construct certain public types?

### ISSUE THREAD

**Issue by jadamcrain** [CycloneDX/cyclonedx-rust-cargo#227]
I would like to use [cyclonedx-bom](https://crates.io/crates/cyclonedx-bom) to construct my own custom BOMs.  There are some [limitations](https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/226) with the existing cargo tool that are pushing me in this direction.

I'm struggling to figure out how to construct certain types in the model however. Namely:

* [DateTime](https://docs.rs/cyclonedx-bom/0.3.2/cyclonedx_bom/external_models/date_time/struct.DateTime.html)
* [Purl](https://docs.rs/cyclonedx-bom/0.3.2/cyclonedx_bom/external_models/uri/struct.Purl.html) and [Uri](https://docs.rs/cyclonedx-bom/0.3.2/cyclonedx_bom/external_models/uri/struct.Uri.html).

These newtypes have `pub(crate)` members, no constructors, and I can't find any conversion traits like from/try_from to create them.

I figured I could just look at the cargo application, but then I discovered that it doesn't even use the `cyclonedx-box` crate in the same workspace.... it has it's own parallel implementation of the data structures! What's the thinking there?

**Comment by amy-keibler** [comment]
Sorry for the delayed response; I have been on vacation this week. Currently, we're in the middle of replacing the partial specification implementation in `cargo-cyclonedx` with a new, complete one (`cyclonedx-bom`). You can read about the current progress in #68. Currently, the library supports serialization and deserialization, but is lacking UX polish and documentation. I've been working on documentation and @allisonsierra has been working on the integration between `cargo-cyclonedx` and `cyclonedx-bom`. If you have specific feedback or would like to contribute, I'd appreciate it.

As for the newtypes, the intent is to avoid having third party crates as a part of our public API where possible to allow us to swap out dependencies as needed over time.

**Comment by jadamcrain** [comment]
Thanks @amy-keibler.  Using newtypes to hide implementation details makes sense, I just couldn't figure out how to construct them at all.

When the cargo executable starts using this crate for the implementation, I'm sure this will work itself out.

**Comment by jadamcrain** [comment]
Hi @amy-keibler. Checking in on this issue. It looks like the cargo command now depends on `cyclonedx-bom`.  Do you think it would be worthwhile for me to try using `cyclonedx-bom` to create my own BOMs now?

**Comment by amy-keibler** [comment]
Hi, @jadamcrain. Thanks for following up. I think that it would be worthwhile for you to try using `cyclonedx-bom` at this point and let us know if you run into any further issues. we've been working on writing documentation for the library and using that to ensure that every type can be constructed via a user of the library, but we're not quite done yet and so there might be parts of the library that are unused by the CLI that still might have rougher edges.

**Comment by jadamcrain** [comment]
Awesome. I will give it a try in the next few weeks and provide feedback here. If I run into easily fixed issues I will start a running PR.

**Comment by jadamcrain** [comment]
Hi @amy-keibler.  I've been successful in using `cyclonedx-bom` 0.4.0 to generate from my own custom filtering of the build manifest.

The only thing keeping me from using the cargo plugin is https://github.com/CycloneDX/cyclonedx-rust-cargo/issues/230.

Closing this issue as resolved, ty.
