### ISSUE TITLE
External reference urls should be inside a <url> tag

### ISSUE THREAD

**Issue by sduquette-devolutions** [CycloneDX/cyclonedx-rust-cargo#24]
The URLs are currently placed directly inside the reference tag, they should be inside a <url> tag.

Example:

```
<reference type="documentation">https://docs.rs/base64</reference>
```

instead of

```
<reference type="documentation"><url>https://docs.rs/base64</url></reference>
```

**Comment by DarthHater** [comment]
@sduquette-devolutions I'm going to close this given your PR was merged! Feel free to open if I'm in error
