### ISSUE TITLE
Rename the executable to cargo-cyclonedx

### ISSUE THREAD

**Issue by sduquette-devolutions** [CycloneDX/cyclonedx-rust-cargo#29]
Commands can be added to cargo when an executable named `cargo-<command>` is in path. For example, `cargo cyclonedx` will call cargo-cyclonedx. The generated executable name could be changed by adding the following section in Cargo.toml.

```
[[bin]]
name = "cargo-cyclonedx"
path = "src/main.rs"
```

That said it would be even better to use the package name `cargo-cyclonedx`, it is available on crates.io.

**Comment by DarthHater** [comment]
This is not a bad idea. @stevespringett wdyt? It would simplify execution as a `cargo` subcommand from my perspective.

**Comment by stevespringett** [comment]
I'm for it

**Comment by stevespringett** [comment]
Although I'm not sure about changing the package name on cargo. We don't want multiple packages up there.

**Comment by DarthHater** [comment]
FTR I don't think you need to change the package name to do this, but I'm not entirely 100% positive about that. For `cargo-pants` we have multiple subcommands that work, it's mostly just configuration of the executable and what it responds to (so using `clap` or something akin to say "ok do something when the subcommand `sbom` or `cyclonedx` is detected).

**Comment by sduquette-devolutions** [comment]
As far as I know a command is called based on the executable name, so to handle "cargo cyclonedx" the executable needs to be called cargo-cyclonedx. It is possible to handle sub-commands, "cargo cyclonedx diff" for example.
https://doc.bccnsoft.com/docs/rust-1.36.0-docs-html/cargo/reference/external-tools.html#custom-subcommands

The reason I suggest renaming the package is that packages usually follow that convention and that's what Rust users will look for first.

**Comment by 06kellyjac** [comment]
> This is achieved by translating a cargo invocation of the form cargo (?<command>[^ ]+) into an invocation of an external tool cargo-${command} that then needs to be present in one of the user's $PATH directories.
https://github.com/rust-lang/cargo/wiki/Third-party-cargo-subcommands

Yep `cargo-something` can be executed through `cargo something`

**Comment by amy-keibler** [comment]
This has been tested and resolved via PR #32. Thanks!

**Comment by sduquette-devolutions** [comment]
Thanks Amy!
