### ISSUE TITLE
Feature Request: Generate BOM from cargo-auditable embedded dependency information

### ISSUE THREAD

**Issue by taladar** [CycloneDX/cyclonedx-rust-cargo#315]
The [auditable-info](https://docs.rs/auditable-info/latest/auditable_info/) crate allows the retrieval of dependency information embedded in a Rust binary via [cargo-auditable](https://lib.rs/crates/cargo-auditable).

The related [quitters](https://docs.rs/quitters/latest/quitters/) crate tries to reconstruct dependency information from panic messages in the binary (the file paths to be precise).

For details on both see this [reddit post](https://www.reddit.com/r/rust/comments/yk7l3w/cargo_audit_can_now_scan_compiled_binaries/)

It would be useful to be able to generate SBOMs from this information to allow the use of standard CycloneDX tools, e.g. Dependency Track, with previously compiled binaries. The quitters approach could be especially useful with older binaries which do not compile any more to allow a better decision on rewrite vs. update.

**Comment by amy-keibler** [comment]
Thanks for the feature request! I looked at `cargo-auditable` previously, but I didn't see that `auditable-info` existed.

I'm curious what your thoughts are on the potential usecases? If it is intended to scan a binary that has been provided by a third party, my initial thought is that it would probably make sense for us to create a different CLI tool from `cargo-cyclonedx` for that purpose. We'd probably be able to fetch information from `crates.io` to fill in the package metadata, such as license information that doesn't appear to be embedded in the binary, but there are probably fields that the user would have to supply via command line parameters or via a file format for convenience.

**Comment by taladar** [comment]
The use-case for me would be to scan binaries compiled in the past before our CI jobs included cargo-cyclonedx, specifically for some binaries which no longer compile due to yanked crates.

**Comment by Shnatsel** [comment]
This is now implemented in https://github.com/rust-secure-code/cargo-auditable/pull/136 on the `cargo auditable` repo, so I'm going to go ahead and close this.
