### ISSUE TITLE
How to enable "lax" parsing?

### ISSUE THREAD

**Issue by ctron** [CycloneDX/cyclonedx-rust-cargo#321]
Running `cargo cyclonedx` I get tons of errors like this:

```
Package x509-parser has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
```

But how do I enable  "lax parsing"?

```
cargo-cyclonedx 
Creates a CycloneDX Software Bill-of-Materials (SBOM) for Rust project

USAGE:
    cargo cyclonedx [OPTIONS]

OPTIONS:
    -a, --all                                List all dependencies instead of only top-level ones
    -f, --format <FORMAT>                    Output BOM format: json, xml
    -h, --help                               Print help information
        --manifest-path <PATH>               Path to Cargo.toml
        --output-cdx                         Prepend file extension with .cdx
        --output-pattern <PATTERN>           Prefix patterns to use for the filename: bom, package
        --output-prefix <FILENAME_PREFIX>    Custom prefix string to use for the filename
    -q, --quiet                              No output printed to stdout
        --top-level                          List only top-level dependencies (default)
    -v, --verbose                            Use verbose output (-vv very verbose/build.rs output)

```

**Comment by amy-keibler** [comment]
Hi, @ctron . There's an [ongoing discussion](https://github.com/CycloneDX/cyclonedx-rust-cargo/discussions/282) about this (linking to avoid copy-pasting too much text), but the short version is that `MIT/Apache-2.0` is not a valid SPDX license identifier. `cargo-cyclonedx` is making an assumption on your behalf that the library author meant `MIT OR Apache-2.0`, but we want you to be aware that we are converting it to the valid SPDX form when outputting the SBOM, for interoperability purposes.

We've discussed grouping the invalid license expressions and outputting a single warning statement instead of a statement per license, but I'm interested in what your expectations would be as a user of the CLI tool.

**Comment by ctron** [comment]
> We've discussed grouping the invalid license expressions and outputting a single warning statement instead of a statement per license, but I'm interested in what your expectations would be as a user of the CLI tool.

Thanks for the explanation. And thanks for caring! I will comment here, if you think the other issue is the better place, I can move the content over too. Just let me know.

I will use the following example, which is a bit shorter:

```
➜  drogue-client git:(main) cargo cyclonedx && echo ok || echo nok
[2022-11-11T06:47:28Z ERROR cargo_cyclonedx::generator] Package base64 has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
[2022-11-11T06:47:28Z ERROR cargo_cyclonedx::generator] Package chrono has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
[2022-11-11T06:47:28Z ERROR cargo_cyclonedx::generator] Package lazy_static has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
[2022-11-11T06:47:28Z ERROR cargo_cyclonedx::generator] Package reqwest has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
[2022-11-11T06:47:28Z ERROR cargo_cyclonedx::generator] Package url has an invalid license expression, trying lax parsing (MIT/Apache-2.0): Invalid SPDX expression: invalid character(s)
ok
```

My expectations would be:

1. If there is an "error" (and it looks even more serious in the console due to being bold, red) then the application should not end with an "ok" outcome, it should fail. Maybe take some inspiration from others: https://stackoverflow.com/questions/2031163/when-to-use-the-different-log-levels
2. Is this indeed an error? The program still produces output. If it is an error, then it should not produce output. If it is not, then maybe "WARN" is good enough.
3. if the program tells me to "trying lax parsing", then there should be a way for me (the user) to do this (e.g using `--lax`)
4. If there are problematic licenses, then there should be a way to deal with them (e.g. `--lax`, `--ignore-licenses="foo, bar, baz"`, `--map-license=foo=SpdxFoo`, …) Maybe not with program arguments, but with a config file?
5. Having an improved visual representation (rather then just errors in the log) would definitely make the tool more user friendly. Might be overkill, having a table isn't too difficult: https://github.com/ctron/cargo-clearlydefined#ignoring--excluding
