### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by DerekStrickland** [CycloneDX/cyclonedx-rust-cargo#382]
Hello! I'm looking for a CycloneDX crate and found this, but I don't see any commits since January or any recent progress towards supporting 1.4.  Is this project still maintained?

**Comment by stevespringett** [comment]
Yes, this repo is still supported, but like most open source projects, it is volunteer driven. @amy-keibler leads this project.

**Comment by tokcum** [comment]
I've prepared a PR to support 1.4. However, it's huge and not yet ready. I'm awaiting feedback from @amy-keibler on how to progress with it.

**Comment by DerekStrickland** [comment]
Thanks for replying @stevespringett and for your work @tokcum. I'll keep watching, and if I can help in any way, please let me know. I could for instance test out your PR with my use case if it would be helpful and not a distraction.

**Comment by lfrancke** [comment]
We're breathing fresh life into this project right now: https://stackable.tech/en/empowering-rust-projects/
I'm going to close this issue but feel free to reopen at a later point.
Discussions will also stay open.
