### ISSUE TITLE
Make dependency content public.

### ISSUE THREAD

**Issue by alilleybrinker** [CycloneDX/cyclonedx-rust-cargo#409]
As far as I can tell, there's no valid way to extract the dependency information in a `Bom`. The `dependencies` field is public, but it's a newtype struct with a `pub(crate)` field, meaning it's private for other crates. There are no methods to access the internal `Vec` of dependencies, so there's no way to access this field.

I suppose there's a workaround of using the JSON output to get a `serde_json::Value` and then using the `pointer` method to access the field, but this feels excessive for accessing data that's present but unnecessarily private.

**Comment by alilleybrinker** [comment]
`std::mem::transmute` to get the inner type out of the newtype struct also works, but is use of `unsafe` only to get around a privacy mistake in the API.

**Comment by Shnatsel** [comment]
Fixed by #504
