### ISSUE TITLE
Allow access to the spec version

### ISSUE THREAD

**Issue by ctron** [CycloneDX/cyclonedx-rust-cargo#446]
Currently, after parsing an SBOM. The `specVersion` field is not available.

However, what might happen is that the `1.3` parser parses a `1.4` version successfully. However, without reparsing and inspecting the raw JSON (or XML), it seems impossible to check if this was actually a 1.3 or 1.4 document. Which might be necessary to know in some cases.

I can come up with a PR for this if that helps.

**Comment by Shnatsel** [comment]
Hey! I'm helping maintain the repo now. This seems like a reasonable addition, I would be happy to accept a PR that exposes the field if this is still relevant.

**Comment by justahero** [comment]
Hi @ctron ,

sorry for the late reply, do you think the change in PR #583 covers your use case?
