### ISSUE TITLE
Getting different behavior between repo and cargo install

### ISSUE THREAD

**Issue by keponk** [CycloneDX/cyclonedx-rust-cargo#474]
Hi, I have a small project I was trying to run this on. A dummy one with only a handful of dependencies.

I installed the tool with cargo and as per the generated bom it is the `0.3.8` version. But this is presenting the exact problem stated here: https://github.com/CycloneDX/cyclonedx-rust-cargo/pull/443  I don't see the dependencies in the resulting bom file.

I noticed this is supposed to be fixed, and so I tried cloning the repo, compiling and ran the resulting release build, this worked and didn't present the problem shown above. I can see the version is also shown as `0.3.8`. So I'm wondering if there's some mismatch between the version installed by `cargo install` and what is currently on the main branch.

**Comment by lfrancke** [comment]
Hi, 
I'm sorry I'm not entirely sure I understand.

- The released version is 0.3.8 and that doesn't work
- The current main branch works for you?

**Comment by lfrancke** [comment]
Understood! Thank you for the clarification.

When you do `cargo install` you'll get the latest published version which is 0.3.8: https://crates.io/crates/cargo-cyclonedx

Unfortunately, no release has been made with the fixes yet. I'll see what we can do about it.

**Comment by keponk** [comment]
thanks! I also noticed there's no automated cicd here and couldn't find documentation around it. I'm wondering if you have a reason to not have it automated, in other words, that the releases are accompanied by their compiled release target in the 2 or 3 major architectures.
The underlying reason for me is that I'm trying to also use this in my CICD, and getting the cargo version, besides being currently broken, also needs compilation during install, if I could just pull the "official" binary release that would be awesome.
I would be happy to try putting something together but  am wondering if you have your reasons to intentionally not do that.

**Comment by lfrancke** [comment]
This happened before my time but the quick answer is probably because no one has had the time so far :)

You are looking for releases in GitHub, right?

**Comment by keponk** [comment]
Github or you preferred location, I assumed github is the expected location.
Bottom line, the ultimate goal is to generate SBOMs right? this are usually generated during CI process.
So the ability to quickly grab that binary to do it's job during CI would be ideal. Currently the alternatives seem to be
1. cargo install : besides the issue of not having the latest version in it, it takes time to compile
2. Some more convoluted linking to this repo / checkout and also compiling.

The ideal scenario could be to have away to quickly grab/download the release binary and then project wanting to use it during CI can simply run that binary. No compilation required.

**Comment by lfrancke** [comment]
Understood. Makes sense. Thank you!

**Comment by keponk** [comment]
@lfrancke i saw your message on my accidental PR, sorry for the noise. that is still not ready.

would I be creating noise if I try to contribute though? I have a little test going on here:
https://github.com/keponk/cyclonedx-rust-cargo/blob/develop/.github/workflows/deploy_cyclonedx_bom.yml

in that WIP I assumed the moment you publish and tag, is probably the moment you want to release as well.
So I create release builds (smaller than the regular cargo build) and zip them and create the release with the same name of the tag.  These in the 3 main archs (win/lin/mac). in the process also added rust cache action so save _a lot_ of time during CICD.

maybe we can close this ticket which has now evolved. I could create a new one just dedicated to the publish/release process.  or, let me know if i should just wait for whatever your team is working on.

**Comment by lfrancke** [comment]
Absolutely no noise at all. We appreciate all help.

I just wanted to make @Shnatsel aware of this, he can say better whether he already did something here or not.

**Comment by Shnatsel** [comment]
I have not looked at modifying the workflows in any detail yet. 

The workflows for Github releases (as opposed to crates.io) are not on my radar, so your work isn't going to conflict with mine.

Using the `rust-cache` action sounds like a very good idea. I've used it before and saw very good results. I would appreciate having that as a separate PR, independent of the release workflow changes.

**Comment by keponk** [comment]
hi, I've pushed a PR with the cache setup-only. It requires the CI to run once successfully, after that the speed improvements should be immediately noticeable.

Regarding the binaries release, I have a working setup, just an issue when compiling for windows that was a bit outside my knowledge and would take me longer to debug. But the pipeline of publishing & tagging > building a _release_ version > creating release binaries (for linux64 and macos64) are ready as well.

**Comment by lfrancke** [comment]
Excellent, thank you.
Not having windows is still better than not having anything!

**Comment by lfrancke** [comment]
Can this issue be closed?

We'll do a new release soon which includes all kinds of changes.
