### ISSUE TITLE
CLI arguments are not used

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#48]
The following arguments are supported via the command-line, but are not used:

- `target_dir`
- `verbose`
- `quiet`
- `color`
- `frozen`
- `locked`
- `offline`
- `unstable_flags`
- `config_args`

They are [passed to `cargo::util::Config::configure`](https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/e79a24f81e7a063930434c365764ebf58217733e/src/main.rs#L118), which is only used to get the current working directory in

```rust
let manifest = args
        .manifest_path
        .unwrap_or_else(|| config.cwd().join("Cargo.toml"));
```

I think we probably want to support:

- `verbose`
- `quiet`

and probably drop the rest, as they don't have an effect on SBOM generation (e.g. we're always offline, because we don't download anything from the internet).

We should also consider what other CLI arguments we want to support.

- I think a `--output` would be useful so the user can specify a particular location to store the SBOM rather than defaulting to the current working directory
- Looking at [the Python CycloneDX repository](https://github.com/CycloneDX/cyclonedx-python), I think a `--force` flag would be a good idea to allow users more control on overwriting existing output.
- `--include-dev-dependencies` and `--include-license-text` seem like good options as well, from [the CycloneDX Node repository](https://github.com/CycloneDX/cyclonedx-node-module)

**Comment by coderpatros** [comment]
Sounds good to me. Maybe an obsolete message for options that are being dropped.

**Comment by coderpatros** [comment]
Although maybe we should include dev dependencies by default. So the option would be --exclude-dev-dependencies. I think they should be included by default but marked as optional.
