### ISSUE TITLE
SBOM configuration via `Cargo.toml` appears harmful

### ISSUE THREAD

**Issue by Shnatsel** [CycloneDX/cyclonedx-rust-cargo#495]
Right now `cargo-cyclonedx` will read some of its configuration from the `Cargo.toml` of the project it is run on. That is, the developers rather the user who runs the tool determine what kind of output it will produce.

For example, if the user expects XML files (as per the default) but the project contains a directive to output JSON, the configuration in `Cargo.toml` will override the default, and an unusable SBOM will be generated.

It will be even worse if we default to reporting all dependencies in the future, but a `Cargo.toml` file specifies reporting only direct dependencies; in this case the SBOM will silently be incomplete, creating security and compliance issues.

I believe the possibility of the configuration to be specified by anyone other than the person actually using the tool is a fundamentally flawed approach, and all such means of configuration should be removed.

@lfrancke thoughts?

**Comment by lfrancke** [comment]
I tend to agree with you. Good catch! I didn't even think of that.

So, the suggestion is to remove the option to configure via `Cargo.toml` entirely? I think I'm good with that. I'll ask in Slack if anyone has any opinions on this but if we don't hear anything in a few days I'd say we can remove it.

**Comment by Shnatsel** [comment]
Removed in #520
