### ISSUE TITLE
Allow for inter-project dependencies

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#50]
A common practice for Cargo workspace projects is to include both a `version` and `path` for inter-project dependencies (example: [`tokio-stream` depends on `tokio`](https://github.com/tokio-rs/tokio/blob/d047584e86c7235f17084d3115325e4a99a4f761/tokio-stream/Cargo.toml#L33)). This allows local development to make changes across the project without publishing, while also allows for an easy publish workflow when crates depend on each other.

Right now we do

```rust
// Filter out our own workspace crates from dependency list
for member in members {
    dependencies.remove(member);
}
```

and

```rust
if members.contains(&package) {
    // Skip listing our own packages in our workspace
    continue;
}
```

which would mean that `tokio` would be excluded from the BOM for `tokio-stream`. This doesn't match [the `tokio-stream` dependencies list](https://crates.io/crates/tokio-stream/0.1.7/dependencies), which might be confusing to users in the context of the changes for PR #33 (create a separate BOM for each cargo workspace member).

#### Suggested change

Add a CLI argument to override the current behavior for when projects want to explicitly list dependencies from the same project. Something like `--include-inter-workspace-dependencies`

**Comment by lfrancke** [comment]
I believe this is something that now works out of the box.
Inter-project dependencies should be included by default.

@Shnatsel?

**Comment by Shnatsel** [comment]
I'm not sure how this is implemented currently, I'll need to either dig into the code or test it.

**Comment by Shnatsel** [comment]
`cargo cyclonedx` no longer has the behavior described here, i.e. this was fixed at some point.
