### ISSUE TITLE
Add support for `cargo binstall`

### ISSUE THREAD

**Issue by liamwh** [CycloneDX/cyclonedx-rust-cargo#552]
As described [here](https://github.com/cargo-bins/cargo-binstall/blob/main/SUPPORT.md), so that `cargo-binstall` doesn't attempt to install cargo-cyclonedx from source:
![image](https://github.com/CycloneDX/cyclonedx-rust-cargo/assets/23312359/134ee46f-143c-49a3-b24e-ba3a5565a584)

**Comment by lfrancke** [comment]
Are you willing or interested in providing a PR for this?

**Comment by tshepang** [comment]
cargo-dist would make providing such extra easy

**Comment by Shnatsel** [comment]
I'd be happy to have a PR for it! We should also update the repo's README listing it as a possible installation option.

It'd be great to get a release workflow with `cross` going for building aarch64 binaries as well, but that's a separate issue (cc @keponk )

**Comment by ashleygwilliams** [comment]
put a PR up- cargo-dist can add the release instructions to the release body- but i'm also happy to add the installers to the README once we decide which ones you want to support.

**Comment by liamwh** [comment]
I've had a really great experience automating releases using [release-plz](https://github.com/MarcoIeni/release-plz). I believe it's even simpler than `cargo-dist`, although I don't have any firsthand experience with `cargo-dist` myself. However I can recommend using release-plz, I found it extremely easy to use and have no complaints with it. Maybe it's helpful here?

**Comment by ashleygwilliams** [comment]
hey @liamwh - release plz is great and i think it can be a good tool for generating changelogs, but it doesn't have functionality for building standalone releases or generating installers. many folks use release-plz with cargo-dist for changelog generation. the main thing that cargo-dist is doing here is building binaries and then archiving those binaries for a variety of platforms, then generating installers for them.

**Comment by ashleygwilliams** [comment]
i believe that this was solved by #727 !
