### ISSUE TITLE
Extend metadata via user input

### ISSUE THREAD

**Issue by ModestMannfred** [CycloneDX/cyclonedx-rust-cargo#607]
Look at the following documents:
https://www.ntia.gov/files/ntia/publications/ntia_sbom_framing_2nd_edition_20211021.pdf
https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf

We think that the following minimum baseline attributes are missing from the sbom.

- /metadata/authors (of the SBOM)
- /metadata/Supplier
- /metadata/component/publisher

It is possible to parse the author name and email, using appropriate the Cargo.toml field, however, this is the author of the package, not the author of the SBOM. We think the SBOM author should be independent of the package. We could create a program to parse the output and add the missing fields, however, we thought it might be nicer to provide this possibility via cargo-cyclonedx. Has this issue been already considered elsewhere and rejected?

Initial suggestion would be to include a CLI flag (eg. --metadata-extension-path) for specifying a metadata extension file in XML or JSON, which includes override metadata in the SBOM specified format, eg.:
```
{
  "authors": [
    {
      "name": "SbomAuthor",
      "email": "SbomAuthor@company.com",
      "phone": "6345789"
    }
  ],
  "component": {
    "publisher": "Developer, Inc."
  }
  "supplier": {
    "name": "Supplier, Inc.",
    "url": [
      "https://www.supplierco.com"
    ],
    "contact": [
      {
        "name": "Supplier",
        "email": "contact@supplier.com",
        "phone": "6345789"
      }
    ]
  }
}
```

This way it also is flexible enough for format changes. Poorly formed entries are ignored / rejected.

Interested in your feedback and open to other implementations and/or clarifications. We can implement.

**Comment by Shnatsel** [comment]
I'm actually not convinced that adding CLI flags for this is a good idea.

CycloneDX is a standardized format, so if you get a stable interface to interact with any part of it. You can write a tool that applies the desired transformation once, and then use it with any generator or anything that speaks CycloneDX. 

By contrast, if we start adding CLI flags for various fields, that's a damn lot of fields and damn lot of flags; and these flags would be specific to every generator and would have to be separately implemented in every generator, and you would have to figure out the right flags for every generator as a user - as opposed to just running a CycloneDX editing tool on any CycloneDX file.

**Comment by Shnatsel** [comment]
> Write a script or program which takes the CycloneDX output and modifies it (adds the missing fields). <- It seems to me this is the intended approach

Indeed, this is the approach I would recommend, if feasible. If it is infeasible for some reason for a given field, please let me know and I'll look into that on a case-by-case basis.

**Comment by ModestMannfred** [comment]
We are proceeding as proposed by @Schnatsel
