### ISSUE TITLE
Split the project into separate crates to support reuse

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#68]
Right now, the project is published under a single crate [`cyclonedx-sbom`](https://crates.io/crates/cyclonedx-bom). The dependencies required for the full functionality of the CLI result in a very large dependency tree and large compile times (mostly due to the dependency on `cargo` due to some things not being available via `cargo_metadata`).

### We should split the project into two crates:

- `cyclonedx-sbom`: A lightweight library that implements the specification and provides small utilities (e.g. proposed merge algorithm implementations would live here)
- `cargo-cyclonedx`: The current functionality, but structured in a way that makes the library easy to integrate with other rust applications and makes the binary as the first-party implementation on top.

### Proposed Approach

- [x] Preparation
  - [x] Reserve the `cargo-cyclonedx` crate
  - [x] Set up the [`cdx-automation`](https://crates.io/users/cdx-automation) user with publish access to that crate
- [x] Restructuring
  - [x] Create a workspace and move the existing code to `cargo-cyclonedx/`
  - [x] Update CI and publishing to work
- [ ] Library-ification
  - [ ] Implement the specification library
    - [x] Create an internal model that will be the public API for use by `cargo-cyclonedx` and other Rust applications
    - [x] Create a private model of every version of the specification that supports serialization and deserialization (can this be auto-generated?)
    - [x] Create the mapping between the public and private models
    - [ ] Create utility functions to deserialize from any version of the specification, serialize as the latest version, and serialize as a specific version
    - [x] Support validation (perhaps via something like [`Keats/validator`](https://github.com/Keats/validator)
  - [x] Set up CI
    - [x] Ensure the tests run on PRs and pushes
    - [x] Set up the publish GitHub actions to handle releasing the library (this should Just Work with [the `publish crates`](https://github.com/marketplace/actions/publish-crates) action we currently use, but more research needs to be done to determine specifying major / minor / patch versions.
- [ ] Documentation
  - [ ] `README.md` for each crate
  - [ ] Top level readme
  - [ ] Rustdoc

### Concerns

- This will change the `cargo install` command and might cause problems with users who have already installed the CLI tool
- This will break anyone using our code as a library. This is _permissible_ under SemVer ([reference](https://semver.org/#spec-item-4)) and we have zero [public reverse dependencies](https://crates.io/crates/cyclonedx-bom/reverse_dependencies), but might not be appreciate
  - We should look into ways to mitigate this in general by having a public channel for comments that our users can watch for updates
  - This would definitely be at least a minor version increase, but we could also consider releasing a `1.0.0` version

**Comment by amy-keibler** [comment]
Work on this is underway in the [`library-ification`](https://github.com/CycloneDX/cyclonedx-rust-cargo/tree/library-ification) branch for anyone who would like to follow along

**Comment by lfrancke** [comment]
I know this is an old issue but do you happen to remember what's not available via `cargo_metadata`?

**Comment by lfrancke** [comment]
I think this can be closed as it's been done. Any objections?

@Shnatsel opinions?
