### ISSUE TITLE
`cyclonedx_bom::models::tool::Tool` misses `external_references` introduced in v1.4

### ISSUE THREAD

**Issue by nikstur** [CycloneDX/cyclonedx-rust-cargo#703]
The `Tool` type doesn't have an `external_references` field which was introduced in v1.4. See: https://cyclonedx.org/docs/1.4/xml/#type_toolType

It'd be nice if I can construct a Tool with external references in [`bombon`](https://github.com/nikstur/bombon)

**Comment by lfrancke** [comment]
Thank you! We will fix this in time for the next release (which we plan very soon)
