### ISSUE TITLE
0.5.2: lock file is not updated

### ISSUE THREAD

**Issue by dvzrv** [CycloneDX/cyclonedx-rust-cargo#728]
Hi! :wave: 

I package this project for Arch Linux. When trying to upgrade to 0.5.2 I noticed that the lock file has not been updated:
https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/23e466654da141a05d8d4240fe14f8159913a938/Cargo.lock#L230

For packaging purposes we want to fetch the locked sources, but this is unfortunately not possible:

```bash
$ cargo fetch --locked --target "$(rustc -vV | sed -n 's/host: //p')"
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/user/Downloads/cyclonedx-rust-cargo/cargo-cyclonedx/Cargo.toml
workspace: /home/user/Downloads/cyclonedx-rust-cargo/Cargo.toml
    Updating crates.io index
error: the lock file /home/user/Downloads/cyclonedx-rust-cargo/Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, remove the --locked flag and use --offline instead.
```

**Comment by lfrancke** [comment]
@dvzrv Thank you very much for your packaging work! And thanks @Shnatsel for taking care of the release.
