### ISSUE TITLE
Replace lazy_static with once_cell

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#73]
Replace [`lazy_static`](https://crates.io/crates/lazy_static) with [`once_cell`](https://crates.io/crates/once_cell).

`lazy_static` is unmaintained and the API used by `once_cell` is being integrated into the standard library ([tracking issue](https://github.com/rust-lang/rust/issues/74465). Switching to this library now will hopefully make the adjustment to using the standard library version require minimal work.

### Acceptance Criteria

- [ ] The unmaintained dependency is replaced and removed
- [ ] If possible, the new use removes the use of `.expect` calls for the regular expressions and converts any errors to `Result` style code.

**Comment by allisonsierra** [comment]
I'm interested in working on this one.
