### ISSUE TITLE
`models::tool::Tools::Object` should have `Option<>` fields

### ISSUE THREAD

**Issue by nikstur** [CycloneDX/cyclonedx-rust-cargo#730]
The [`Tools::Object` variant](https://docs.rs/cyclonedx-bom/latest/cyclonedx_bom/models/tool/enum.Tools.html
) should have `Option<Services>` and `Option<Components>` fields just like the top-level `Bom` struct. Otherwise, you cannot construct `Tools` without declaring both `Services` and `Components`.

**Comment by justahero** [comment]
Hello,

thanks for your report. The recent PR #732 should fix the issue. If you see that it does not solve your issue, please comment here.

**Comment by lfrancke** [comment]
I'll close this issue for now as I believe it has been fixed as @justahero mentioned.
