### ISSUE TITLE
Configurable alternate output location needed for read-only source trees

### ISSUE THREAD

**Issue by joell** [CycloneDX/cyclonedx-rust-cargo#775]
### Problem
I cannot generate a BOM for a Rust source tree residing on a read-only filesystem, writing the BOM to a separate write-able filesystem.

### Analysis
Currently, a BOM's file output path is always made relative to the `Cargo.toml` manifest provided on input:

https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/d11ec27e1bf2420f4f48ce628e4c663325787f45/cargo-cyclonedx/src/generator.rs#L812-L817

Further, it is not possible to avoid this by giving an absolute-path `--override-filename` because configuration checks prohibit path separator characters:

https://github.com/CycloneDX/cyclonedx-rust-cargo/blob/d11ec27e1bf2420f4f48ce628e4c663325787f45/cargo-cyclonedx/src/config.rs#L174-L177

This results in cyclonedx-rust-cargo always trying to write BOMs to the directory the `Cargo.toml` resides in, which in my use case is read-only and thus results in an IO error.

### Suggestion
Would it be possible to add a CLI option for explicitly setting an alternate output directory that BOM files will be written to?  (At first I thought `--override-filename` would do that, until I discovered it just sets a filename prefix and not a full path.)

**Comment by Shnatsel** [comment]
That's not really feasible.

First, `cargo cyclonedx` runs `cargo metadata`, which in turn may modify the `Cargo.lock` file. That's fundamentally incompatible with a read-only filesystem already.

Second, there may be name collisions between crates and/or binaries within a workspace. We deliberately place SBOM files in the crate directory to avoid name collisions. If we put all SBOMs in one directory, we have to either clobber some SBOM files in case of name collisions or introduce some complex disambiguation scheme that anyone who wants to read the SBOMs would have to support.

**Comment by joell** [comment]
`cargo metadata --locked` is an option which never modifies `Cargo.lock`, and a failure due to out-of-date lockfile could simply translate to a failure of the tool.  So it need not be an impediment to read-only filesystem compatibility.

Regarding generation of multiple SBOMs simultaneously, yes that would require a solution to naming collisions; but any multi-output scenario can be decomposed into one or more single-output cases.  Already, for the default `--describe=crate` scenario, only a single SBOM is generated.  Likewise, for multi-target crates if an option were added that allowed selecting a single crate target, only a single SBOM need be generated.

In these single-SBOM output cases, collision in an output directory would not be a concern.  In fact, it would even allow for an alternate option of simply writing the single SBOM to stdout, which would eliminate the need for an output directory entirely (since single UNIX-style redirection or piping could deal with consuming the output).

This seems like it might be accomplished by adding only two new CLI options:

1. A `--describe single-cargo-target=<TARGET>` suboption, to handle multi-target crates.
2. A `--stdout` option, which would only be valid in single-SBOM cases, and would write the SBOM directly to stdout.

Would you be open to considering adding an approach along these lines in order to support read-only source trees?

**Comment by Shnatsel** [comment]
>  Already, for the default `--describe=crate` scenario, only a single SBOM is generated.

Unfortunately no, you can have multiple crates in a workspace.

And to make use of the single-target mode, you'd need to specify which target you want to describe, which would require the caller to enumerate the targets, so they'd have to run something like `cargo metadata` themselves and parse the output just to use `cargo cyclonedx`.

Between having the caller deal with all of that complexity, and having the caller copy the project to a writable location, the latter seems far simpler, and also more robust since it doesn't fail if the Cargo.lock isn't up to date. Or, if copying is somehow infeasible, you could mount the project directory with OverlayFS.

**Comment by joell** [comment]
Alright.  Thank you for considering this.

[To anyone else on the Internet with a similar problem finds this thread in the future: My use case was solved by finding [cargo-sbom](https://github.com/psastras/sbom-rs) which can handle read-only source trees and writes to stdout.]
