### ISSUE TITLE
Replace StructOpt with clap

### ISSUE THREAD

**Issue by amy-keibler** [CycloneDX/cyclonedx-rust-cargo#93]
We use [`StructOpt`](https://crates.io/crates/structopt) for our CLI parser library. Its functionality has been added to one of its dependencies, [`clap`](https://crates.io/crates/clap) in its `3.0.0` release. `StructOpt` is now in [maintenance mote](https://github.com/TeXitoi/structopt#maintenance), so we should switch over to `clap`. This should mostly translate directly, but there might be a few changes required

### Acceptance Criteria

- [ ] The `structopt` dependency is replaced with `clap = "3.0.10"`
- [ ] Existing CLI functionality is preserved or improved

**Comment by allisonsierra** [comment]
I will work on this one.
